### ISSUE TITLE
Evaluate elastic graph analytics

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#127]
As I learned today from @literarymachine, [Elastic opened up "X-Pack"](https://www.elastic.co/de/products/x-pack/open) which includes [graph analytics](https://www.elastic.co/products/x-pack/graph). It definitely makes sense to play around with this, maybe starting with an exploration interface for the GND relations graph.

**Comment by acka47** [comment]
Related to #66

**Comment by acka47** [comment]
@droi At https://www.elastic.co/guide/en/kibana/current/graph-getting-started.html it says "Graph is automatically enabled in Elasticsearch and Kibana". I can't see it in our Kibana instance though. Why is that? Do we need to install a newer version?

**Comment by acka47** [comment]
I now found out that you have to start a 30 days license trial to get the Graph feature, see https://www.elastic.co/guide/en/kibana/current/managing-licenses.html That's what I did locally and it worked. Anyway, this contradicts what is said at https://www.elastic.co/guide/en/kibana/current/graph-getting-started.html.

**Comment by acka47** [comment]
> At https://www.elastic.co/guide/en/kibana/current/graph-getting-started.html it says "Graph is automatically enabled in Elasticsearch and Kibana". I can't see it in our Kibana instance though. Why is that? Do we need to install a newer version?

We are running Kibana 5.6.3 and obviously you have to install xpack in this version. See https://www.elastic.co/guide/en/x-pack/5.6/installing-xpack.html for instructions.

**Comment by dr0i** [comment]
Installing , but as this also needs the ES-Cluster using X-Pack and because of our configuration it is not possible to upgrade smoothly, thus I added a new ES-node to weywot1 since two nodes are sufficient to have all indices complete (adding one => 4 nodes (of which 2 are the old ones (without X-Pack) and the other 2 _with_ X-Pack. This configuration is only temporarily needed, and if the 2 with X-Pack are running (i.e. not yet) I will add the 3 node to it to have a failsafe cluster.)

However, you _can_ already use kibana with X-Pack , but as this comes without SSL please only use the internal URI:
http://weywot1.hbz-nrw.de:5601
Username is "elastic" and the password is the same for the piwik-user in "matomo".

You can play with e.g. "graph".
Note:

> Your Trial license is active
> Your license will expire on October 10, 2018 3:51 PM CEST.
> 
>Unlock the Full Functionality
>Get all X-Pack has to offer: security, monitoring, alerting, reporting, and Graph, plus support from the engineers behind the Elastic Stack.

So it seems that the `graph` is not coming for free.

**Comment by acka47** [comment]
http://etherpad.lobid.org/p/elastic-lizenzen-if22x39v

**Comment by dr0i** [comment]
Our current cluster configuration don't allow an easy downtime-free upgrade (best would be to have a second free server: weywot2 (an ES2.6-node for lobid.organisation is running there but will be shutdown at the end of october ). As it's not clear at the moment if we go with licening the graph or an other solution (see also https://github.com/hbz/lobid/issues/382) this issue is postponed for at least until the shutdown of lobid-organisations 1.0.
