### ISSUE TITLE
Interruptions of batch download

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#205]
Reported by @Kordishal via email:

> Seit ca. einer Woche kann ich bei einem Request auf die Batch API von 
> euch Zugreiffe nicht mehr das ganze File herunterladen.
> 
> 
> Der Download wird immer nach einer weile abgebrochen. Dabei habe ich 
> kein Muster erkannt, wie lange es funktioniert. Manchmal passiert
> 
> das schon nach ein paar MB manchmal erst nach ein paar hundert!
> 
> 
> Ich habe es sowohl mit der Python request Library als auch Curl versucht.
> 
> 
> Eine Vermuttung von mir ist, dass ich den Service überbeansprucht habe 
> da ich beim testen sehr oft das Datenset neu geladen habe (was jetzt 
> nicht mehr
> 
> passiert). Oder es existiert ein anderes Problem.
> 
> 
> Das python script findet ihr hier: 
> https://gitlab.com/swissbib/linked/linking/download-gnd
> 
> 
> Der curl Befehl:
> 
> `curl --header "Accept-Encoding: gzip" "http://lobid.org/gnd/search?q=type:DifferentiatedPerson&format=jsonl" > "/swissbib_index/data/dumps/gnd/gnd-individualisierte-personen-test-2019-06-03.gz"`

**Comment by acka47** [comment]
Assigning @fsteeg as @dr0i thinks this is a Play problem.

**Comment by dr0i** [comment]
Maybe correlated to https://github.com/hbz/lobid/issues/188.

**Comment by fsteeg** [comment]
I can't reproduce this. Downloaded it 3 times (from outside the hbz network) with no problems. The files are 965M, the number of lines in the gunzipped jsonl file match the number of hits for the plain query.

@Kordishal: Could this be a problem on your side, e.g. on the machine you're downloading to (like disk space) or something related to your network? Can you test with a different machine, or from a different network? If it happens again, could you send us the exact time so we can try to find something in our logs?

> Maybe correlated to hbz/lobid#188.

In lobid-gnd we use Play 2.6, which uses a different implementation for streamed responses (Akka Streams, used since 2.5, see https://www.playframework.com/documentation/2.6.x/Highlights25#New-streaming-API-based-on-Akka-Streams), replacing the Iteratees-based approach that had memory issues (https://groups.google.com/d/msg/play-framework-dev/58VZD-YXdJw/axByShRsff4J).

**Comment by Kordishal** [comment]
Ok this time it worked. Unfortunately I do not have the times of the old downloads saved.

Space on disk is not full at all. Will report again should it happen again, but can be closed until then.
