### ISSUE TITLE
Reconcilation Service don't return right Types.

### ISSUE THREAD

**Issue by boerni667** [hbz/lobid-gnd#211]
When i've tried out your reconcilation service, it always returned for every hit a list of types, but all types which are supported by your reconcilation services and not the specific type of the hit. 

Shouldn't the given example just return the object for "Work" as the type of the first hit in the result array?

e.g. `curl --data 'queries={"q1":{"query":"Goethe"}}' http://lobid.org/gnd/reconcile`
returns 
```json
{
  "q1": {
    "result": [
      {
        "id": "1154419746",
        "name": "Goethe",
        "score": 25.306683,
        "match": true,
        "type": [
          {
            "id": "AuthorityResource",
            "name": "Normdatenressource"
          },
          {
            "id": "CorporateBody",
            "name": "K��rperschaft"
          },
          {
            "id": "ConferenceOrEvent",
            "name": "Konferenz oder Veranstaltung"
          },
          {
            "id": "SubjectHeading",
            "name": "Schlagwort"
          },
          {
            "id": "Work",
            "name": "Werk"
          },
          {
            "id": "PlaceOrGeographicName",
            "name": "Geografikum"
          },
          {
            "id": "DifferentiatedPerson",
            "name": "Individualisierte Person"
          },
          {
            "id": "Family",
            "name": "Familie"
          }
        ]
      },
...
]}}
```

**Comment by acka47** [comment]
Thanks for the report. I am not very familiar with the API and @fsteeg, who implemented the API, is currently on vacation so that we won't be able to take a deeper look into this until next week.

@boerni667, how are you using the reconciliation service? With the [OpenRefine client](http://openrefine.org/download.html) or in another way?

Trying this out by myself with the OpenRefine client (version 3.1), I get the expected result (i.e. only type that apply not all top types) when reconciling some strings against GND via lobid and adding the type of reconciled entries via "Edit column" --> "Add columns from reconciled values...". Thus, I am not sure whether this really is a bug.

**Comment by fsteeg** [comment]
@boerni667 Thanks for finding and reporting this issue, it is now fixed in production, see https://lobid.org/gnd/reconcile?queries={"q0":{"query":"Goethe"}}

The effect is that in the reconciliation dialog (after selecting the service), only types are suggested that are actually in the results for the values we are reconciling.

**Comment by boerni667** [comment]
Yes i've experienced this same issue (only types are suggested which are in the first batch of result after selecting) also when i was developing our openrefine reconcilation API for our very own LOD service API. I think this is an bug for openrefine, they should suggest all the defaultTypes defined in the service metadata.

**Comment by fsteeg** [comment]
Hm, I thought of it as a feature, since it only suggests types that will actually yield results.
