### ISSUE TITLE
Add labels to ID fields

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#24]
For example http://test.lobid.org/authorities/118506560.

Currently looks like:

```json
{
"professionOrOccupation": [
  "http://d-nb.info/gnd/4131406-2",
  "http://d-nb.info/gnd/4012434-4"
  ]
}
```

With added labels:

```json
{
   "professionOrOccupation":[
      {
         "id":"http://d-nb.info/gnd/4131406-2",
         "preferredName":"Pianist"
      },
      {
         "id":"http://d-nb.info/gnd/4012434-4",
         "preferredName":"Dirigent"
      }
   ]
}
```

However, there are several other cases (e.g. `placeOfDeath`, `relatedWork`, `familialRelationship`) where we only have internal GND links without labels in the data. Thus, a general approach would probably make sense to automatically add a label for _all_ URIs from the `http://d-nb.info/gnd/` namespace. (If we implement a general approach, it should be possible to exclude some properties from this label enrichment, e.g. we might get problems with trying to fetch the label for `deprecatedUri` and also labels for `sameAs` links within GND aren't necessary I think.) What do you think, @fsteeg?

**Comment by fsteeg** [comment]
From the logic/implementation view this should work. We already get labels for GND URIs in the UI. We could use the previous index data when running a transformation. It would significantly increase processing runtime however, since we'd have to analyze every record for values to add, and issue multiple index requests for each record.

**Comment by fsteeg** [comment]
Full list of ID fields to add labels for (taken from #26):

- professionOrOccupation
- placeOfBusiness
- placeOfConferenceOrEvent
- firstAuthor (firstComposer etc.)
- geographicAreaCode (depends on #17)
- gndSubjectCategory (depends on #17)

**Comment by fsteeg** [comment]
Data deployed to test: http://test.lobid.org/gnd/118506560.json

@acka47 You can already take a look at the data if you want to. I will continue in this issue with: 

1. Fixing the indexing problems due to the object structure that I mentioned earlier in our call
3. UI updates to use the new labels from the data, replacing API calls for labels in the UI

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/118506560.json

**Comment by acka47** [comment]
+1
