### ISSUE TITLE
Support URI switch to https

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#243]
From the [announcement](https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20190703AenderungFormatRdf20193.pdf?__blob=publicationFile&v=3):

> In allen Komponenten des Linked-Data-Services der ZDB und der DNB wird das Protokoll HTTP durch HTTPS ersetzt. Hintergründe zu dieser Entscheidung im [WIKI der DINI-AG Kompetenzzentrum Interoperable Metadaten](https://wiki.dnb.de/display/DINIAGKIM/HTTP+vs.+HTTPS+in+resource+identification).
>
> Betroffen sind im einzelnen:
> - DNB-Titel Profil „DINI-AG KIM-Empfehlungen“
> - ZDB-Titel Profil „DINI-AG KIM-Empfehlungen“
> - ISIL- und Sigelverzeichnis
> - GND Profil „GND-Ontology“
> - Entity Facts
> - Alle RDF-Elementsets (GND-Ontology, DNB-Metadata-Terms, Agent
Relationship Ontology)
> - Alle RDF-Value-Vocabularies (GND-Geschlecht, GND-Ländercodes, GNDSystematik, GND-Koordinatentyp)
>
> Ausgenommen ist vorerst nur der BIBFRAME-Prototyp, da er im nächsten Release grundlegend überarbeitet wird.

The changes were deployed "in der KW 42, 2019 voraussichtlich im Laufe des 15. Oktober 2019" (see [here](https://lists.dnb.de/pipermail/lds/2019-July/000145.html)).

**Comment by acka47** [comment]
W.G. on 2019-10-22 reported problems with a newly created GND record which might be related to the switch:

> eine Kollegin hat letzten Mittwoch in der GND Daten 
> erfasst, die über Lobid aktuell noch nicht recherchierbar sind. Der Link 
> lautet http://d-nb.info/gnd/1197147705

As of today, this entry is still not in lobid-gnd: https://lobid.org/gnd/1197147705

**Comment by fsteeg** [comment]
The missing updates are now in production, but still with `http` URIs: https://lobid.org/gnd/1197147705.

We will be switching to `https` URIs when they are available from https://data.dnb.de/opendata/.

(Missing updates were due to a change in xmlns setup in the RDF/XML, see https://github.com/hbz/lobid-gnd/commit/6eea15f3fd851b15648f043322b84d5927e42512.)

(New `variantName` language tags are ignored for API compatibilitiy, see https://github.com/hbz/lobid-gnd/commit/eaa7ff0d3bb7d0dba690e674833f6f5d8ef915bd.)

Assigning @acka47 for review, but we should leave this open for the actual switch to `https` URIs.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
A new dump (from 2019-10-13) is now available, see https://lists.dnb.de/pipermail/lds/2019-November/000157.html & https://data.dnb.de/opendata/

**Comment by fsteeg** [comment]
- [ ] Index `20191013` EntityFacts dump
- [ ] Convert and index `20191013` GND dump
- [ ] Handle `https` URIs
- [ ] Update apps using lobid-gnd

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd

**Comment by acka47** [comment]
On Friday, we published a blog post about the change, see http://blog.lobid.org/2019/11/29/lobid-gnd-https-change.html. To be deployed on 2019-12-12.
