### ISSUE TITLE
Missing entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#270]
Reported by P.M. today via email: 

> Kürzlich bin ich auf eine weitere Ungereimtheit beim Reconciling gestossen, folgende (individualisierte)  GND-Datensätze sind via lobid nicht auffindbar:
>  
> Guilhemat, Bertrand$$dca. 1760-18XX    (DE-588)1212391691
> Gorsas, Marie-Madeleine$$dca. 1793-1800      (DE-588)1212460715
> Provost, P.  (DE-588)1212480465
> Pain, Pierre-Honoré-Antoine$$d1755-18XX      (DE-588)1212481844
> König, Amand        (DE-588)1212459776
> Finsler, Johann     (DE-588)1213477573
> Typis Schaufelbergerianis$$gZürich     (DE-588)1213907543
> Simmlerische Druckerei    (DE-588)121392250X
> Officina Wolfiana (DE-588)1213941202
>  
> Ich habe im GND-RDF keinen Grund erkennen können (das heisst allerdings nichts).

These entries aren't in lobid-gnd at all although they are part of the GND:

- https://d-nb.info/gnd/1212391691 -> https://lobid.org/gnd/1212391691
- https://d-nb.info/gnd/1212460715 -> https://lobid.org/gnd/1212460715
- https://d-nb.info/gnd/1212480465 -> https://lobid.org/gnd/1212480465
- https://d-nb.info/gnd/1212481844 -> https://lobid.org/gnd/1212459776
- https://d-nb.info/gnd/1212459776 -> https://lobid.org/gnd/1213477573
- https://d-nb.info/gnd/1213477573 -> https://lobid.org/gnd/1213907543
- https://d-nb.info/gnd/1213907543 -> https://lobid.org/gnd/121392250X
- https://d-nb.info/gnd/121392250X -> https://lobid.org/gnd/1212481844
- https://d-nb.info/gnd/1213941202 -> https://lobid.org/gnd/1213941202

**Comment by acka47** [comment]
Some of them share the date of last modification (MARC `005`):
- 20200716
- 20200709
- 20200623
- 20200622

I assume, something must have gone wron with the updates on these dates (and possible other dates).

**Comment by fsteeg** [comment]
Did a full updates conversion and indexing since last baseline (2020-06-22), looks good:

- https://d-nb.info/gnd/1212391691 -> https://lobid.org/gnd/1212391691
- https://d-nb.info/gnd/1212460715 -> https://lobid.org/gnd/1212460715
- https://d-nb.info/gnd/1212480465 -> https://lobid.org/gnd/1212480465
- https://d-nb.info/gnd/1212481844 -> https://lobid.org/gnd/1212459776
- https://d-nb.info/gnd/1212459776 -> https://lobid.org/gnd/1213477573
- https://d-nb.info/gnd/1213477573 -> https://lobid.org/gnd/1213907543
- https://d-nb.info/gnd/1213907543 -> https://lobid.org/gnd/121392250X
- https://d-nb.info/gnd/121392250X -> https://lobid.org/gnd/1212481844
- https://d-nb.info/gnd/1213941202 -> https://lobid.org/gnd/1213941202

Some daily updates in June, July and August were empty (see `sol@quaoar1:~/git/lobid-gnd/data/backup`). I guess there was some effect of the problem mentioned in https://github.com/hbz/lobid-gnd/issues/267#issuecomment-691044214 interfering with the manual reindexing for https://github.com/hbz/lobid-gnd/issues/258. In the future, an issue like this should be caught by the additional checks introduced in https://github.com/hbz/lobid-gnd/issues/260.

**Comment by acka47** [comment]
+1 Closing.
