### ISSUE TITLE
Exclude some entries from being shown on start page

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#301]
At https://lobid.org/gnd we show an image from a random GND entry with each page load. User A.K. notified me via email on 2022-01-06 that this leads to problems with some entries:

> Vielleicht ist es nicht ganz unproblematisch einfach zufällig Bilder aus 
> der Wikipedia auf der Homepage zu zeigen. Ich war mir im ersten Moment 
> nicht sicher, ob die Seite vielleicht gehackt wurde.

The reason: When he visited https://lobid.org/gnd the image of https://lobid.org/gnd/1012979-0 was shown. We should think about an option to write down a list of entries that should not be shown on the start page.

**Comment by fsteeg** [comment]
Deployed to test, can be configured in application.conf:

https://github.com/hbz/lobid-gnd/blob/e2b4e0c5cc9fa469fe128e3d3b08cc24fafe9175/conf/application.conf#L6

**Comment by fsteeg** [comment]
Yeah, that's why I didn't include a link, just the way this is configured :-) I tested with local data, where only 4 records have depictions, and it looked good. You can also take a look at the way the query is built, starting here: https://github.com/hbz/lobid-gnd/blob/e2b4e0c5cc9fa469fe128e3d3b08cc24fafe9175/app/controllers/HomeController.java#L124
