### ISSUE TITLE
Date is not up to date

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#311]
On 02.05.22 17:26, @kkrebs wrote via email:
> ich finde leider die folgende (neu eingetragene) GND nicht:
> https://d-nb.info/gnd/1256359521

The resource in question was created on 2022-04-28 so at least some recent updates haven't made it to lobid-gnd.

**Comment by fsteeg** [comment]
Hm, yes, the 2022-04-29 update contained only a single entry, [1256433276](http://lobid.org/gnd/1256433276).

I re-ran updates since 2022-04-28 and it's in: https://lobid.org/gnd/1256359521 (and 1431 more).

My guess is there was some issue in the GND-LDS resulting in that single-entry update on 2022-04-29.

**Comment by acka47** [comment]
+1 Closing

**Comment by acka47** [comment]
If something like this reoccurs, we will have to add additional checks monitoring the number of records provided by the OAI-PMH interface.
