### ISSUE TITLE
Add lobid gnd page to the JSON Data

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-gnd#404]
I saw that the json data of lobid gnd has no direct statement to the lobid gnd page. I thought this could be added under `sameAs`.

**Comment by acka47** [comment]
lobid-gnd only publishes data originally provided by DNB (GND RDF plus EntityFacts) and until we refrained from adding anything to it. I don't think we even have a process set up to add custom data so that it might take some time. Did anybody of the lobid customers ask for this feature? If not, I think we should close this issue.

**Comment by TobiasNx** [comment]
This was just me. I thought that this would be a nice feature. Simple adding could be done by the elasticSearch. But anyway. I am closing this for now.
